import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';

import SubmissionTable from '../components/SubmissionTable';
import { supabase } from '../lib/supabase';

export default function Submissions() {
  const [submissions, setSubmissions] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchSubmissions();
  }, []);

  async function fetchSubmissions() {
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('submissions')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        console.error('Fetch error:', error);
        toast.error('Failed to load submissions.');
        return;
      }

      setSubmissions(data || []);
    } catch (err) {
      console.error('Fetch error:', err);
      toast.error('Failed to load submissions.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-5">
        <div>
          <h1 className="text-xl font-semibold text-gray-100">Submissions</h1>
          <p className="text-sm text-gray-500 mt-0.5">
            All pathway recommendations generated by the engine.
          </p>
        </div>
        <button
          onClick={fetchSubmissions}
          disabled={loading}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-gray-400 hover:text-gray-200 bg-gray-900 hover:bg-gray-800 border border-gray-700 transition-colors duration-150 disabled:opacity-50"
          id="refresh-submissions"
        >
          <svg
            className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`}
            fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}
          >
            <path strokeLinecap="round" strokeLinejoin="round" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
          </svg>
          Refresh
        </button>
      </div>

      <SubmissionTable submissions={submissions} loading={loading} />
    </div>
  );
}
